# Generated by Django 3.1.4 on 2021-05-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='detail',
            new_name='details',
        ),
    ]
