# Generated by Django 3.1.7 on 2021-05-24 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_auto_20210521_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'permissions': [('can_enter_admin_panel', 'Can enter admin')]},
        ),
    ]
